// import { ITodoType } from '~shared/types/todo/todo.types';

// export const mockDataTodos: ITodoType[] = [
// 	{
// 		id: 1,
// 		title: 'make forst request',
// 		text: 'lorem ipsum dolor lorem ipsum dolorlorem ipsum dolor ',
// 		isCompleted: false,
// 		isPublic: false,
// 		userId: 1,
// 	},
// 	{
// 		id: 2,
// 		title: 'make second request',
// 		text: 'lorem ipsum d',
// 		isCompleted: true,
// 		isPublic: false,
// 		userId: 1,
// 	},
// 	{
// 		id: 3,
// 		title: 'make third request',
// 		text: 'lorem ipsum dolor lorem ipsum dolorlorem ipsum dolor',
// 		isCompleted: true,
// 		isPublic: true,
// 		userId: 1,
// 	},
// 	{
// 		id: 12,
// 		title: 'qq__moo sdasd asd',
// 		text: ' since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially',
// 		isCompleted: false,
// 		isPublic: false,
// 		userId: 1,
// 	},
// 	{
// 		id: 4,
// 		title: 'make 4 request',
// 		text: 'okey',
// 		isCompleted: false,
// 		isPublic: false,
// 		userId: 2,
// 	},
// 	{
// 		id: 6,
// 		title: 'postman',
// 		text: 'tes still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).',
// 		isCompleted: false,
// 		isPublic: false,
// 		userId: 2,
// 	},
// 	{
// 		id: 7,
// 		title: 'asdasda sdasd asd',
// 		text: 'new req',
// 		isCompleted: true,
// 		isPublic: false,
// 		userId: 2,
// 	},
// 	{
// 		id: 8,
// 		title: 'asdasda sdasd asd',
// 		text: 'new req',
// 		isCompleted: false,
// 		isPublic: false,
// 		userId: 2,
// 	},
// 	{
// 		id: 10,
// 		title: 'asdasda sdasd asd',
// 		text: 'new retrue truetrue true ADAD sdad q',
// 		isCompleted: false,
// 		isPublic: true,
// 		userId: 2,
// 	},
// 	{
// 		id: 13,
// 		title: 'asdasda sdasd asd',
// 		text: 'new req',
// 		isCompleted: true,
// 		isPublic: false,
// 		userId: 2,
// 	},
// 	{
// 		id: 16,
// 		title: 'asdasda sdasd asd',
// 		text: 'new req',
// 		isCompleted: true,
// 		isPublic: false,
// 		userId: 2,
// 	},
// 	{
// 		id: 5,
// 		title: 'eat a cake',
// 		text: 'tes still in their infancy. Various v over the years, sometimes by accident, sometimes on purpose (injected ',
// 		isCompleted: false,
// 		isPublic: true,
// 		userId: 3,
// 	},
// ];
